[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_vrf = "9rQm8b1ynr4kww3mA8AbhESnvQXgoPAQMgTih8t4pkoD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/illiafedotov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
